Repository PCL-Community/PCL2-Github-Info-Dashboard, pull requests merged in 2024-04, with the labels that each got.

#1 Create main.js
  main.js
Labels: √ 完成

#8 UI v1.0.0
  .github/workflows/static.yml
  .gitignore
  .vscode/extensions.json
  README.md
  chart.js
  index.html
  jsconfig.json
  main.js
  package-lock.json
  package.json
  public/chart.js
  public/favicon.ico
  src/App.vue
  src/common/fetchIssue.js
  src/common/render.js
  src/components/PageHeader.vue
  src/main.js
  vite.config.js
Labels: ⇵ 正在处理

#10 v1.0.1
  .gitignore
  README.md
  src/App.vue
  src/common/render.js
  src/components/PageHeader.vue
Labels: ⇵ 正在处理, ✦ 建议

#13 v1.0.2
  package.json
  src/App.vue
  src/common/fetchIssue.js
  src/components/PageHeader.vue
Labels: ⇵ 等待处理

#17 v1.0.3
  src/common/render.js
Labels: √ 完成, ✦ 建议

#9 加速获取 issue 列表
  index.html
  src/common/fetchIssue.js
Labels: ✦ New, ⏱️等待
